version: "3"

services:
  web:
    command: "python3.8 webvep/code/manage.py runserver 0.0.0.0:8000"
    image: "vep_api"
    build: .
    stop_signal: SIGINT # The devserver only stops on SIGINT.
    stdin_open: true
    tty: true
    volumes:
      - ./webvep:/opt/vep/src/ensembl-vep/vepweb/code
      - $HOME/vep_data:/opt/vep/.vep
    ports:
      - "8000:8000"
