# Generated by Django 3.0.4 on 2020-03-22 03:20

from django.db import migrations, models
import vcfupload.models


class Migration(migrations.Migration):

    dependencies = [
        ('vcfupload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadvcf',
            name='file',
            field=models.FileField(upload_to=vcfupload.models._obfuscate_uploaded_filename, verbose_name='Uploaded Vcf'),
        ),
    ]
