# Generated by Django 3.0.4 on 2020-03-22 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcfupload', '0002_obfuscate_filenames_20200322_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadvcf',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='Filename as POSTed by user'),
        ),
    ]
